# Generated by Django 5.1.1 on 2024-10-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_movil', models.IntegerField(unique=True, verbose_name='Numero Movil')),
                ('institucion_id', models.IntegerField(verbose_name='ID de institucion')),
                ('activa', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
